### PR TITLE
UI Fixes and resolved #806, #980

### LINKED ISSUE #806: Space between tabs should be the same when tabs are expanded
- [x] between all tabs

- [x] including when tabs are expanded

Screenshot 2020-06-29 at 15 36 24

### PR DESCRIPTION
**Pull request by farmanahmed2007**

### CODE REVIEW

File: src/components/build/investigationBuildPage/buildQuestions/questionPanelWorkArea.tsx [hunk 1]
```diff
@@ -175,17 +175,15 @@ const QuestionPanelWorkArea: React.FC<QuestionProps> = ({
                     (index >= 1) ?
                       <Grid container justify="center" alignContent="flex-start">
                         <div className="right-side-text">Last Question?</div>
-                        <Button
+                        <button
```
Comment (scholar6admin) [inline src/components/build/investigationBuildPage/buildQuestions/questionPanelWorkArea.tsx:178]: Standard convention is to use a capital at the start of a component.

File: src/components/play/brick/baseComponents/MathInHtml.tsx [hunk 2]
```diff
@@ -18,22 +18,18 @@ class MathInHtml extends Component<MathHtmlProps> {
     }
 
     if (arr.length === 0) {
-      return <div>{this.props.value}</div>;
+      return <div >{this.props.value}</div>;
     }
 
     return (
-      <div>
-        {
```
Comment (scholar6admin) [inline src/components/play/brick/baseComponents/MathInHtml.tsx:26]: This makes me uncomfortable because it feels like a bracket is missing here somewhere. How would you feel about creating a Jest test for this https://jestjs.io/docs/en/tutorial-react

Comment (william-gooch) [reply src/components/play/brick/baseComponents/MathInHtml.tsx:26]: Before this commit the section was missing a closing brace, but after this commit it seems fine as far as I can tell.
